spring:
  security:
    user:
      name: admin
      password: # 원하는 비밀번호로 설정
  datasource:
    url: jdbc:h2:tcp://localhost/~/fruitsfarm-BE
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

logging.level:
  org.hibernate.SQL: debug